title: 3D Gaussian Splatting Reading Group
url: ""
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Theme by <a href='https://github.com/ankitsultana/researcher'>researcher</a>" 

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"